name: List Files in the Repo

on:
  push:

jobs:
  list:
    runs-on: ubuntu-latest
    steps:
    #action@version
      - name: Checkout The Repo
        uses: actions/checkout@v4
        
      - name: List Files in Root
        run: ls -a
